# This is a workflow to install k3s and other needed services for my rasberry pi kubernetes cluster. The following will be installed and configured:
# 1. k3s server on master node
# 2. k3s agent on worker nodes
# 3. Helm
# 4. MetalLB (bare metal load balancer)
# 5. Nginx 
# 6. cert-manager

name: Configure Kubernetes Cluster

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      testInput1:
        description: 'Test Input #1'     
        required: true
        default: 'someValue'
      testInput2:
        description: 'Test Input #2'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
